import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "ترولي راتان بشاسيه خشبي ثلاثي الأدوار - أسود بيج",
    price: 449,
    originalPrice: 550,
    image: "https://cdn-ai.onspace.ai/onspace/files/38eNVnZLRZvTMRdCCha3sx/1000119127.jpg",
    category: "تروليات راتان",
    color: "أسود بيج",
    dimensions: "18×51×93 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان أنيق بشاسيه خشبي ثلاثي الأدوار، مثالي للتخزين المنزلي الأنيق. مصنوع من الراتان عالي الجودة بإطار خشبي متين.",
  },
  {
    id: "2",
    name: "ترولي راتان بشاسيه خشبي ثلاثي الأدوار - فوشيا أبيض",
    price: 449,
    originalPrice: 550,
    image: "https://cdn-ai.onspace.ai/onspace/files/KnzHW65qXir2viZgZnmExL/1000119122.jpg",
    category: "تروليات راتان",
    color: "فوشيا أبيض",
    dimensions: "18×51×93 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان عصري بألوان الفوشيا والأبيض المبهجة، ثلاثي الأدوار بشاسيه خشبي متين.",
  },
  {
    id: "3",
    name: "ترولي راتان بشاسيه خشبي ثنائي الأدوار - أسود",
    price: 329,
    originalPrice: 400,
    image: "https://cdn-ai.onspace.ai/onspace/files/TDkKB6un2jLVqddKKH2AQw/1000119128.jpg",
    category: "تروليات راتان",
    color: "أسود",
    dimensions: "54×31.5×38.5 سم",
    tiers: 2,
    inStock: true,
    description: "ترولي راتان ثنائي الأدوار بإطار خشبي أسود، مدمج ومناسب للمساحات الصغيرة.",
  },
  {
    id: "4",
    name: "ترولي راتان بشاسيه خشبي ثنائي الأدوار - بني",
    price: 329,
    originalPrice: 400,
    image: "https://cdn-ai.onspace.ai/onspace/files/ZfuJZ2Q7iQqVXXsh6ZAQr6/1000119119.jpg",
    category: "تروليات راتان",
    color: "بني",
    dimensions: "54×31.5×38.5 سم",
    tiers: 2,
    inStock: true,
    description: "ترولي راتان ثنائي الأدوار بألوان بنية دافئة وإطار خشبي متين.",
  },
  {
    id: "5",
    name: "ترولي راتان مستطيل ثلاثي الأدوار - بني فاتح",
    price: 389,
    originalPrice: 470,
    image: "https://cdn-ai.onspace.ai/onspace/files/MEZLNQNBDyy46EYtAVS5kA/1000119168.jpg",
    category: "تروليات راتان",
    color: "بني فاتح",
    dimensions: "46×75×15 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان مستطيل ثلاثي الأدوار بلون بني فاتح أنيق، مثالي للصالون والغرف.",
  },
  {
    id: "6",
    name: "ترولي راتان مستطيل ثلاثي الأدوار - أسود نحاسي",
    price: 399,
    originalPrice: 490,
    image: "https://cdn-ai.onspace.ai/onspace/files/Vqzguv9JaXemWGBkHbQ5eH/1000119143.jpg",
    category: "تروليات راتان",
    color: "أسود",
    dimensions: "20×46×75 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان مستطيل فاخر بتفاصيل نحاسية على خلفية سوداء أنيقة.",
  },
  {
    id: "7",
    name: "ترولي راتان مستطيل ثلاثي الأدوار - بني داكن",
    price: 419,
    originalPrice: 510,
    image: "https://cdn-ai.onspace.ai/onspace/files/jC6rda6PwqDjvENzrVuN5X/1000119135.jpg",
    category: "تروليات راتان",
    color: "بني داكن",
    dimensions: "105×40×30 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان مستطيل كبير ثلاثي الأدوار، بلون بني داكن راقٍ ومساحة تخزين واسعة.",
  },
  {
    id: "8",
    name: "ترولي راتان مستطيل ثلاثي الأدوار - هافان",
    price: 419,
    originalPrice: 510,
    image: "https://cdn-ai.onspace.ai/onspace/files/9cBWoAw5Nso3u8WaW4qBDe/1000119111.jpg",
    category: "تروليات راتان",
    color: "هافان",
    dimensions: "105×40×30 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان مستطيل بلون الهافان الكلاسيكي الدافئ، ثلاثي الأدوار بتصميم أنيق.",
  },
  {
    id: "9",
    name: "ترولي راتان مستطيل متحرك بالعجلات ثلاثي الأدوار - تركواز",
    price: 447,
    originalPrice: 530,
    image: "https://cdn-ai.onspace.ai/onspace/files/6fpc9DcQDvRpaKJtqCiddr/1000119163.jpg",
    category: "تروليات بعجلات",
    color: "تركواز",
    dimensions: "25×50×108 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان مستطيل متحرك بعجلات سهلة الحركة، ثلاثي الأدوار بلون تركواز مميز.",
  },
  {
    id: "10",
    name: "ترولي راتان مستطيل متحرك بالعجلات ثلاثي الأدوار - بيج أبيض",
    price: 447,
    originalPrice: 530,
    image: "https://cdn-ai.onspace.ai/onspace/files/B6xcLYAKmfqMUFnHQXTQUo/1000119152.jpg",
    category: "تروليات بعجلات",
    color: "بيج أبيض",
    dimensions: "25×50×108 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان أنيق بألوان البيج والأبيض المتحرك بعجلات سلسة، ثلاثي الأدوار.",
  },
  {
    id: "11",
    name: "ترولي راتان مستطيل متحرك بالعجلات ثلاثي الأدوار - رمادي أبيض",
    price: 447,
    originalPrice: 530,
    image: "https://cdn-ai.onspace.ai/onspace/files/3DcqzgWFcAYkvfXXJjp8dz/1000119148.jpg",
    category: "تروليات بعجلات",
    color: "رمادي أبيض",
    dimensions: "25×50×108 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان متحرك بعجلات، ثلاثي الأدوار بألوان الرمادي والأبيض العصرية.",
  },
  {
    id: "12",
    name: "ترولي راتان مستطيل متحرك بالعجلات ثلاثي الأدوار - أسود",
    price: 447,
    originalPrice: 530,
    image: "https://cdn-ai.onspace.ai/onspace/files/4u8WGoXC9dKiHoqL4KL7di/1000119133.jpg",
    category: "تروليات بعجلات",
    color: "أسود",
    dimensions: "25×50×108 سم",
    tiers: 3,
    inStock: false,
    description: "ترولي راتان أسود متحرك بعجلات، ثلاثي الأدوار بتصميم أنيق وعصري.",
  },
  {
    id: "13",
    name: "ترولي راتان بعجلات متحرك ثلاثي الأدوار - بيج",
    price: 389,
    originalPrice: 470,
    image: "https://cdn-ai.onspace.ai/onspace/files/iPExCpuuaRHf4gYTcHUSiR/1000119157.jpg",
    category: "تروليات بعجلات",
    color: "بيج",
    dimensions: "85×45×30 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان ثلاثي الأدوار بعجلات متحركة ولون بيج دافئ وأنيق.",
  },
  {
    id: "14",
    name: "ترولي راتان مستطيل ثلاثي الأدوار - أبيض أسود",
    price: 459,
    originalPrice: 560,
    image: "https://cdn-ai.onspace.ai/onspace/files/B6xcLYAKmfqMUFnHQXTQUo/1000119152.jpg",
    category: "تروليات راتان",
    color: "أبيض أسود",
    dimensions: "83×48×38 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان مستطيل ثلاثي الأدوار بتباين أبيض وأسود أنيق.",
  },
  {
    id: "15",
    name: "ترولي راتان مزود بغطاء ثلاثي الأدوار - أسود",
    price: 469,
    originalPrice: 570,
    image: "https://cdn-ai.onspace.ai/onspace/files/TDkKB6un2jLVqddKKH2AQw/1000119128.jpg",
    category: "تروليات راتان",
    color: "أسود",
    dimensions: "83×48×38 سم",
    tiers: 3,
    inStock: true,
    description: "ترولي راتان أسود فاخر مزود بغطاء علوي، ثلاثي الأدوار لتخزين أنيق.",
  },
  {
    id: "16",
    name: "وحدة أدراج راتان ثلاثية الأدراج - أسود بني",
    price: 379,
    originalPrice: 460,
    image: "https://cdn-ai.onspace.ai/onspace/files/joEKWTxAYdqTvctp6v2Cxt/1000119115.jpg",
    category: "وحدات أدراج",
    color: "أسود بني",
    dimensions: "37×47×81 سم",
    tiers: 3,
    inStock: true,
    description: "وحدة أدراج راتان ثلاثية بألوان أسود وبني، تصميم أنيق لتنظيم المنزل.",
  },
  {
    id: "17",
    name: "وحدة أدراج راتان ثلاثية الأدراج - بني داكن",
    price: 379,
    originalPrice: 460,
    image: "https://cdn-ai.onspace.ai/onspace/files/9cBWoAw5Nso3u8WaW4qBDe/1000119111.jpg",
    category: "وحدات أدراج",
    color: "بني داكن",
    dimensions: "37×47×81 سم",
    tiers: 3,
    inStock: true,
    description: "وحدة أدراج راتان بني داكن فاخرة، ثلاثة أدراج واسعة للتخزين المنظم.",
  },
  {
    id: "18",
    name: "شانون نيت ناشيونال رباعي الأدوار - بني وردي",
    price: 329,
    originalPrice: 399,
    image: "https://cdn-ai.onspace.ai/onspace/files/KnzHW65qXir2viZgZnmExL/1000119122.jpg",
    category: "وحدات تخزين",
    color: "بني وردي",
    dimensions: "37×86 سم",
    tiers: 4,
    inStock: true,
    description: "وحدة شانون نيت ناشيونال رباعية الأدوار بأربع عجلات، بألوان البني والوردي المبهجة.",
  },
  {
    id: "19",
    name: "شانون نيت ناشيونال رباعي الأدوار - أبيض بنفسجي",
    price: 329,
    originalPrice: 399,
    image: "https://cdn-ai.onspace.ai/onspace/files/QVgn6zAgyjEdxvAKQC4YzX/c85de815-d18c-4fc5-bac9-a900644e1fd1-1_all_53567.jpg",
    category: "وحدات تخزين",
    color: "أبيض بنفسجي",
    dimensions: "37×86 سم",
    tiers: 4,
    inStock: true,
    description: "وحدة شانون نيت ناشيونال رباعية بأربع عجلات، ألوان أبيض وبنفسجي لمسة مرحة.",
  },
  {
    id: "20",
    name: "وحدة أدراج الوطنية رباعية الأدوار - روز تركواز",
    price: 349,
    originalPrice: 420,
    image: "https://cdn-ai.onspace.ai/onspace/files/3WpwQFM9gw6B2etmEGfnxc/c85de815-d18c-4fc5-bac9-a900644e1fd1-1_all_53551.jpg",
    category: "وحدات تخزين",
    color: "روز تركواز",
    dimensions: "47×37×90 سم",
    tiers: 4,
    inStock: true,
    description: "وحدة أدراج الوطنية رباعية بألوان الروز والتركواز المميزة، مناسبة للأطفال والبالغين.",
  },
  {
    id: "21",
    name: "رف تخزين الوطنية ثلاثي الأدوار - تركواز",
    price: 299,
    originalPrice: 360,
    image: "https://cdn-ai.onspace.ai/onspace/files/HjTTmJEFNiimYTMut2MYdX/1000119107.jpg",
    category: "رفوف تخزين",
    color: "تركواز",
    dimensions: "86.5×38.5×49.5 سم",
    tiers: 3,
    inStock: true,
    description: "رف تخزين الوطنية ثلاثي الأدوار بلون التركواز المنعش، خفيف ومتين.",
  },
  {
    id: "22",
    name: "رف تخزين الوطنية رباعي الأدوار - بني",
    price: 349,
    originalPrice: 420,
    image: "https://cdn-ai.onspace.ai/onspace/files/AaVMthwj5Ryoc9nqneJuDF/1000119102.jpg",
    category: "رفوف تخزين",
    color: "بني",
    dimensions: "86.5×38.5×49.5 سم",
    tiers: 4,
    inStock: true,
    description: "رف تخزين الوطنية رباعي الأدوار بلون البني الكلاسيكي الدافئ، مناسب لكل غرف المنزل.",
  },
  {
    id: "23",
    name: "رف تخزين بلاستيك رباعي الأدوار - تركواز",
    price: 289,
    originalPrice: 350,
    image: "https://cdn-ai.onspace.ai/onspace/files/Vqzguv9JaXemWGBkHbQ5eH/1000119143.jpg",
    category: "رفوف تخزين",
    color: "تركواز",
    dimensions: "86.5×38.5×49.5 سم",
    tiers: 4,
    inStock: true,
    description: "رف تخزين بلاستيكي رباعي الأدوار بلون التركواز، عملي ومقاوم وسهل التنظيف.",
  },
];

export const categories = ["الكل", "تروليات راتان", "تروليات بعجلات", "وحدات أدراج", "وحدات تخزين", "رفوف تخزين"];
